
export const Users = [
    {
      id:1,
      profilePicture: "assets/person/1.jpg",
      username: "HELPING HANDS",
    },
    {
      id:2,
      profilePicture: "assets/person/2.jpg",
      username: "Edward Scissorhand",
    },
    {
      id:3,
      profilePicture: "assets/person/3.jpg",
      username: "Dina Byrnes",
    },
    {
      id:4,
      profilePicture: "assets/person/4.jpg",
      username: "Bobbie Boucher",
    },
    {
      id:5,
      profilePicture: "assets/person/5.jpg",
      username: "Harry Potter",
    },
    {
      id:6,
      profilePicture: "assets/person/6.jpg",
      username: "Katie McCallister",
    },
    {
      id:7,
      profilePicture: "assets/person/7.jpg",
      username: "Forrest Gump",
    },
    {
      id:8,
      profilePicture: "assets/person/8.jpg",
      username: "Dewey Finn",
    },
    {
      id:9,
      profilePicture: "assets/person/9.jpg",
      username: "Doug Carlin",
    },
    {
      id:10,
      profilePicture: "assets/person/10.jpg",
      username: "Kajuunn Navy",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Someone may need your help, can you lend a hand today?",
      photo: "assets/post/1.png",
      date: "5 mins ago",
      userId: 1,
      check: 10,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      desc: "I can cut everyone's else hair but my own. Can someone help me?",
      date: "15 mins ago",
      userId: 2,
      check: 1,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Could use some extra hands cleaning up. Anyone available?",
      photo: "assets/post/3.jpg",
      date: "1 hour ago",
      userId: 3,
      check: 0,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      desc: "Is anyone in need of high quality H20? Please let me know. I deliver.",
      photo: "assets/post/4.jpg",
      date: "4 hours ago",
      userId: 4,
      check: 2,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      desc: "I'm available to do house chores. It's just a flick of the wrist.",
      photo: "assets/post/5.jpg",
      date: "5 hours ago",
      userId: 5,
      check: 200,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      desc: "Due to unforeseen circumstances, I'm out of the country! In need of a good babysitter, one that can housesit with a kid!",
      photo: "assets/post/6.jpg",
      date: "1 day ago",
      userId: 6,
      check: 1,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "If you ever need a running partner, I'm just a call a way.",
      photo: "assets/post/7.jpg",
      date: "2 days ago",
      userId: 7,
      check: 10,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      desc: "In need of someone to help sanitize my classrooms after school each day. Any volunteers? This is a great community service for any highschoolers!",
      photo: "assets/post/8.jpg",
      date: "3 days ago",
      userId: 8,
      check: 5,
      like: 20,
      comment: 6,
    },
    {
      id: 9,
      desc: "Anyone in NOLA? We need help cleaning up!",
      photo: "assets/post/9.jpg",
      date: "5 days ago",
      userId: 9,
      check: 2,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      desc: "Don't hesitate to drop your location if you ever need us!",
      photo: "assets/post/10.jpg",
      date: "2 years ago",
      userId: 10,
      check: 25,
      like: 104,
      comment: 12,
    },
  ];
  